FROM debian:trixie-slim
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates kicad kicad-footprints kicad-symbols \
 && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["kicad-cli"]
